#!/usr/bin/env bash
# Usage: prax stop
# Summary: Stop Prax proxy server
set -e

PID=`ps x | awk -F " " "{ if ( \\$5 == \\"ruby\\" && \\$6 == \\"$PRAX_ROOT/lib/prax/command.rb\\" ) print \\$1 }"`
[ "$PID" == "" ] || kill $PID
