#! /usr/bin/env bash
# Usage: prax list
# Summary: Lists all linked hosts in ~/.prax
set -e

for host in $PRAX_HOSTS/* ; do
  if [ -L "$host" ]; then
    path=`readlink "$host"`
    if [ "$PWD" == "$path" ]; then
      echo -n "*"
    fi
    echo "`basename "$host"` '$path'"
  fi
done | sort | sed s,$HOME,~,g | column -t
