#!/usr/bin/env bash
# Usage: prax link [name]
# Summary: Link a Rack application to ~/.prax
# Help: This command will link a Rack application into ~/.prax
#
# By default it will use the name of the current directory, but you may specify
# the name so you can access the same app from different domain names.
#
#   $ cd ~/work/myapp
#   $ prax link
#   ln -f ~/work/myapp ~/.prax/myapp
#   $ prax link othername
#   ln -f ~/work/myapp ~/.prax/othername
#
# For now only Rack applications with a config.ru file can be installed, this
# command will complain until it can find such a file.
set -e

. "$PRAX_ROOT/libexec/shared.sh"
ensure_rack_app "$PWD"

if [ -z "$1" ]; then
  name=`basename "$PWD"`
else
  name="$1"
fi

dest="$PRAX_HOSTS/$name"

if [ -L "$dest" ] ; then
  echo "rm -f '$dest'"
  rm -f "$dest"
fi

echo "ln -s '$PWD' '$dest'"
ln -s "$PWD" "$dest"
