#!/usr/bin/env bash
# Usage: prax start
# Summary: Start Prax proxy server
set -e

# Loads user config (if present)
[ -f "$HOME/.praxconfig" ] && source "$HOME/.praxconfig"

# kills any running instance
prax stop

# keeps a copy of original path (to spawn ruby sub-processes)
export ORIG_PATH="$PATH"

# starts instance
cd "$PRAX_ROOT"
exec "ruby" "$PRAX_ROOT/lib/prax/command.rb" $*
