#!/usr/bin/env bash
# Usage: prax restart [always|never]
# Summary: Restart the current Rack application
set -e

. "$PRAX_ROOT/libexec/shared.sh"
ensure_rack_app "$PWD"

mkdir -p tmp

case $1 in
always)
  echo "touch tmp/always_restart.txt"
  touch tmp/always_restart.txt
  ;;
never)
  echo "rm -f tmp/restart.txt"
  rm -f tmp/restart.txt
  echo "rm -f tmp/always_restart.txt"
  rm -f tmp/always_restart.txt
  ;;
*)
  echo "touch tmp/restart.txt"
  touch tmp/restart.txt
esac
