#!/bin/sh
### BEGIN INIT INFO
# Provides:       prax
# Required-Start: $network $remote_fs $syslog
# Required-Stop:  $network $remote_fs $syslog
# Default-Start:  2 3 4 5
# Default-Stop:   1
# Description:    Prax Rack server (iptables configuration).
### END INIT INFO

set +e   # Don't exit on error status

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/bin/prax
NAME=prax
DESC="Prax Rack server (iptables configuration)."
HTTP_PORT=20559
HTTPS_PORT=20558
DEVICES=$(ifconfig | egrep '^(wlan|eth)[0-9]+' | cut -f1 -d ' ')

case "$1" in
  start)
    if [ `iptables -t nat -L -n | egrep "($HTTP_PORT|$HTTPS_PORT)" | wc -l` -eq 0 ] ; then
      iptables -t nat -A OUTPUT -p tcp -d 127.0.0.1 --dport 80  -j REDIRECT --to-ports $HTTP_PORT
      iptables -t nat -A OUTPUT -p tcp -d 127.0.0.1 --dport 443 -j REDIRECT --to-ports $HTTPS_PORT

      for device in $DEVICES; do
        iptables -t nat -A PREROUTING -p tcp -i $device --dport 80  -j REDIRECT --to-port $HTTP_PORT
        iptables -t nat -A PREROUTING -p tcp -i $device --dport 443 -j REDIRECT --to-port $HTTPS_PORT
      done
    fi
    ;;
  stop)
    RULE_NUMS=`iptables -t nat -L OUTPUT --line-numbers -n | egrep "($HTTP_PORT|$HTTPS_PORT)" | awk '{a[i++]=$0} END { for (j=i-1; j>=0;) print a[j--] }' | awk -F " " '{ print $1 }'`
    for RULE_NUM in $RULE_NUMS ; do
      iptables -t nat -D OUTPUT $RULE_NUM
    done
    RULE_NUMS=`iptables -t nat -L PREROUTING --line-numbers -n | egrep "($HTTP_PORT|$HTTPS_PORT)" | awk '{a[i++]=$0} END { for (j=i-1; j>=0;) print a[j--] }' | awk -F " " '{ print $1 }'`
    for RULE_NUM in $RULE_NUMS ; do
      iptables -t nat -D PREROUTING $RULE_NUM
    done
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    iptables -t nat -L -n
    ;;
esac
